# Generated by Django 4.2.18 on 2025-01-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="content",
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
